# This function has a bug
def add_numbers(a, b):
  # It accidentally multiplies instead of adding
  return a * b
